---
title: "Apresentações/slides"
author:
  - name: Beatriz Milz
    url: https://beatrizmilz.com
    affiliation: PROCAM/IEE/USP
    orcid_id: 0000-0002-3064-4486
date: "Atualizado em `r Sys.Date()`"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(magrittr, include.only = "%>%")
```

```{r metathis, echo=FALSE}
library(metathis)
meta() %>%
  meta_name("github-repo" = "beatrizmilz/slidesR") %>% 
  meta_social(
    title = "Slides sobre R",
    description = paste(
      "Alguns materiais e slides sobre R e comunidades.",
      "Por Beatriz Milz"
    ),
    url = "https://beatrizmilz.github.io/slidesR/",
    image = "https://beatrizmilz.github.io/slidesR/img/share-card.png",
    image_alt = paste(
      "Início do site sobre materiais sobre R e comunidades"
    ),
    og_type = "website",
    og_author = "Beatriz Milz",
    twitter_card_type = "summary_large_image",
    twitter_creator = "@beamilz"
  )
```


```{r}
df_slides <- "slides.csv" %>% 
  readr::read_csv2() %>% 
  dplyr::mutate(data = readr::parse_date(data, format = "%d/%m/%Y"),
                ano = lubridate::year(data))
```

Olá! 

Segue abaixo a lista de apresentações futuras:


```{r}
df_slides %>% 
  dplyr::filter(data > Sys.Date()) %>% 
  dplyr::mutate(url = glue::glue("[{nome}]({link})")) %>% 
  dplyr::select(-ano, -nome, -link) %>% 
  dplyr::relocate(url, .before = 1) %>% 
  dplyr::arrange(desc(data)) %>% 
  knitr::kable(col.names = c("Nome da apresentação", "Idioma", "Data", "Local", "Co-autoria"))
```



Abaixo segue uma lista de links para acessar `r nrow(df_slides)` apresentações feitas sobre R desde 2018. 

```{r echo=FALSE}
df_slides %>% 
  dplyr::filter(data <= Sys.Date()) %>% 
  dplyr::mutate(url = glue::glue("[{nome}]({link})")) %>% 
  dplyr::select(-ano, -nome, -link) %>% 
  dplyr::relocate(url, .before = 1) %>% 
  dplyr::arrange(desc(data)) %>% 
  knitr::kable(col.names = c("Nome da apresentação", "Idioma", "Data", "Local", "Co-autoria"))
```


Além das apresentações apresentadas na tabela anterior, também contribuí com o desenvolvimento do material e/ou dei aulas nas seguintes apresentações:

```{r}
"slides_colaborei.csv" %>% 
  readr::read_csv2() %>% 
  dplyr::mutate(url = glue::glue("[{nome}]({link})")) %>% 
  dplyr::select(-nome, -link) %>% 
  dplyr::relocate(url, .before = 1) %>% 
  dplyr::arrange(desc(ano)) %>% 
  knitr::kable(col.names = c("Nome da apresentação", "Ano", "Comunidade"))
```






```{r}
# df_slides %>%
#   ggplot2::ggplot() +
#   ggplot2::geom_bar(ggplot2::aes(x = ano))
# 
# 
# df_slides %>%
#   ggplot2::ggplot() +
#   ggplot2::geom_bar(ggplot2::aes(x = idioma))
```

