---
title: "naruto"
description: |
  A short description of the post.
author:
  - name: Beatriz Milz
    url: https://beatrizmilz.com
date: 2021-05-19
output:
  distill::distill_article:
    self_contained: false
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


- Obtendo a lista de episódios de Naruto!

```{r}
# url_wiki_naruto <-
#   "https://pt.wikipedia.org/wiki/Lista_de_epis%C3%B3dios_de_Naruto"
# 
# wikipedia_page_naruto  <- rvest::read_html(url_wiki_naruto)
# 
# rvest::html_node(wikipedia_page_naruto, xpath = '//*[@id="mw-content-text"]/div[1]/table[4]') |> 
# rvest::html_table()
# 
# tabela_temporadas_naruto <- seq(4, 20, by = 2)

```


## Naruto Shippuden

```{r}
url_wiki <-
  "https://pt.wikipedia.org/wiki/Lista_de_epis%C3%B3dios_de_Naruto_Shippuden"

wikipedia_page  <- rvest::read_html(url_wiki)

buscar_tabela <- function(n_tabela, n_season) {
  rvest::html_node(
    wikipedia_page,
    xpath = glue::glue('//*[@id="mw-content-text"]/div[1]/table[{n_tabela}]')
  ) |> 
    rvest::html_table() |> 
    janitor::clean_names() |> 
    dplyr::transmute(
      temporada = n_season,
      n_ep = as.character(no),
      titulo = titulo_original,
      data_de_estreia
    )
  }

tabela_temporadas <- seq(4, 42, by = 2)

tabela_suja <-
  purrr::map2_dfr(tabela_temporadas, 1:20, buscar_tabela)


eps_naruto_shippuden <- tabela_suja  |> 
  tidyr::separate(n_ep, into = c("n_ep", "tipo_episodio"), "\\(") |>
  dplyr::mutate(
    n_ep = readr::parse_number(n_ep),
    data_de_estreia = readr::parse_date(
      data_de_estreia,
      format = "%d de %B de %Y",
      locale = readr::locale("pt")
    ),
    tipo_episodio = stringr::str_replace_all(tipo_episodio, "\\)", "")
  ) |>
  tidyr::drop_na(n_ep) |>
  tibble::rowid_to_column() |>
  dplyr::filter(rowid %% 2 != 0) |>
  dplyr::select(-rowid)  |> 
  dplyr::mutate(tipo_episodio = dplyr::case_when(
    is.na(tipo_episodio) ~ "Canon",
    tipo_episodio == "½filler" ~ "Semi-filler",
    TRUE ~ tipo_episodio
  ))
```


```{r}
head(eps_naruto_shippuden)
```

