---
title: "Videos"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



[Conferências](#conferências) -  [Workshops](#workshops) - [Tutoriais](#tutoriais) -  [Lives](#lives)


## Conferências Internacionais


### Evento Latin-R 2020

Título: Transparência em atas de Comitês de Bacias 

<iframe width="560" height="315" src="https://www.youtube.com/embed/K8wmO3mSbU8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Evento <a href="https://user2020.r-project.org/">useR! 2020</a>

Título: Communities of practice in Latin America: R and Friends 

<iframe width="560" height="315" src="https://www.youtube.com/embed/gtRntU2J3Cg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  

### Evento <a href="https://www.user2019.fr/">useR! 2019 Toulouse </a>

Título: The evolution and importance of the R-Ladies São Paulo chapter in Brazil

- Lightning Talk - Education & community 


<iframe width="560" height="315" src="https://www.youtube.com/embed/2HK6hjwhdRk?start=880" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Conferências Nacionais



### Evento Python Brasil 2020

- Ensino de programação: Como fazer parte da comunidade global The Carpentries? - com Mariana Dias Guilardi e Beatriz Milz

<iframe width="560" height="315" src="https://www.youtube.com/embed/jaM88MGaJQM?start=1082" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  


## Workshops

### Latin-R - Comunicando seus resultados com R: aprenda a criar apresentações reprodutíveis


<iframe width="560" height="315" src="https://www.youtube.com/embed/WxKYqtF2qDg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


## Tutoriais

### Joins: juntando bases de dados


<iframe width="560" height="315" src="https://www.youtube.com/embed/xnUo25VRH70" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



## Lives

### Canal Curso-R - Colaborando com a Comunidade

<iframe width="560" height="315" src="https://www.youtube.com/embed/hyLxvGApBJY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Canal Geocast Brasil - R Markdown: usando o R para comunicar seus resultados

<iframe width="560" height="315" src="https://www.youtube.com/embed/6oPZ5sGt6LA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


